spring:
  datasource:
    url: ${GDMT_DATABASE_URL}
    username: ${GDMT_DATABASE_USERNAME}
    password: ${GDMT_DATABASE_PASSWORD}
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

security:
  oauth2:
    resourceserver:
      enable: true
      uri: ${GDMT_IDENTITY_SERVER_URL}
      jwkSetUri: /certs

client-credential:
  client-assertion:
    client-id: ff2f251c-28e5-11ee-be56-0242ac120002
    authentication-server-url: ${GDMT_IDENTITY_SERVER_URL}/token
    token-expiration-time-ms: 900000
  key:
    key-store-base64: ${GDMT_SECRET_CLIENT_ASSERTION_KEYSTORE_BASE64}
    key-store-password-base64: ${GDMT_SECRET_CLIENT_ASSERTION_KEYSTORE_PASS_BASE64}
    key-store-format: JKS
    key-alias: ccpl-gdmt